CC=gcc
RM=rm
FLAGS=-Wall -o

Addition: Addition.c
	$(CC) $(FLAGS) Addition Addition.c

Subtraction: Subtraction.c
	$(CC) $(FLAGS) Subtraction Subtraction.c

Multiplication: Multiplication.c
	$(CC) $(FLAGS) Multiplication Multiplication.c

Division: Division.c
	$(CC) $(FLAGS) Division Division.c
