CC=gcc
RM=rm
FLAGS=-Wall -o

Identify_Positive_Negative: Identify_Positive_Negative.c
	$(CC) $(FLAGS) Identify_Positive_Negative Identify_Positive_Negative.c

Draw_Tree: Draw_Tree.c
	$(CC) $(FLAGS) Draw_Tree Draw_Tree.c

Addition: Addition.c
	$(CC) $(FLAGS) Addition Addition.c

Subtraction: Subtraction.c
	$(CC) $(FLAGS) Subtraction Subtraction.c

Multiplication: Multiplication.c
	$(CC) $(FLAGS) Multiplication Multiplication.c

Division: Division.c
	$(CC) $(FLAGS) Division Division.c

AreaOfCircle: AreaOfCircle.c
	$(CC) $(FLAGS) AreaOfCircle AreaOfCircle.c

AreaOfTriangle: AreaOfTriangle.c
	$(CC) $(FLAGS) AreaOfTriangle AreaOfTriangle.c

SimpleInterest: SimpleInterest.c
	$(CC) $(FLAGS) SimpleInterest SimpleInterest.c

Calculate_Square_Cube: Calculate_Square_Cube.c
	$(CC) $(FLAGS) Calculate_Square_Cube Calculate_Square_Cube.c -lm

Calculate_Total_Average: Calculate_Total_Average.c
	$(CC) $(FLAGS) Calculate_Total_Average Calculate_Total_Average.c

Swap_Two_Numbers: Swap_Two_Numbers.c
	$(CC) $(FLAGS) Swap_Two_Numbers Swap_Two_Numbers.c
